language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: hVGadVa2IglITEJmpW5L3KGNQ2r+ERR8ukOMrdjLvvI5lptdGp090xx2oO0X2ry2fL1T5pftd5TgUJzWWMDe77oT1ANWPP925spe2mNphNTsbThmRskxi2GOneNAZoeoOSzGQgQOT8WF/NjiX6j1sbPqH/G8CzMHDWjI0WnGDh6Epf97aZTcmVupFxo16wqY8yX2Fcd/lZye+TJO7tUxRY5EE0twSrV+4UiEKYdFHizOG5sKLDmx43z9YW2hnlcE3OtbH+w5X2NvFGRTGLMiM9pBHxrlvtmz22eMv6y28CR0j+02YjzBZ1pRtze1VM6MLqzuGZr8O15vwP/A9IaTF9Vlrcp/JfjtblHiO71HVFF5zzUkONOVbKM7FFJB5LLs7VPI23KQ7Um7zaZUd1alYHxc3/tD7JEXxV7ilndtgm3MLeVuf5AWF32k+9KIAvZ3zo7i5xQiqQuRpTWwl3pwajqY0ix2rH5gLjBGgEk80/DUB25AR/JbfJjqhSM+qCfPzi6WKjmdVHl25EUBTYOxqmpine18B5ir1KA1MyXU7eNUerErJTr36CTX6Uw6XEn/TurlTQGXSnk/ItMdvsbuftoezu9QqJ71Y+kAQUSuZLh1N4i1AyiSCFFdbKSeCrGyEQ13SyYZnnYl2gJKE6Kdiok0NCd7ejZht0vwTFBlzTI=
