language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: uSGWuH5e01tyfe6tA7YqWebm4VxL5kAwxqwj4AcKeS9xPcOpzRB+xTt7dm10IM7SLrN9nxWZ+M7v2L68o+QYAsDqxtD2cyErXuMUM7on163nQlG5rPxmaXdIi+qslRxvlQvLdOSeCs8Y3o9+LRX1fjkIGsQcXBCHI+gJd9/YVgxhJ4bYmPgo6K+/nkVnxNMG+qfKTbD5v8bWi4KDssl8nPNjN65rjjuowTC0CPhbH6zY9hIULFgnGiqtCUYAiquCJ+ZO7QZQjVi+Vz3Sn1A66oKgIW7ClSIz6nfE1+pUohBc2C9i8rtIeoiIJeJ7BnXUCh6BI55PxmaWwilJP5U2ZfJ1/cFzrbHjrUQbk4xjmZtKb5CvU0LPPu7S/G/QlOD4ddW38883UKNolUqOVVsrBbZr1MhSphKUyRhQ9geLdAdaxJyy5XzcZ2M9cY1uA+HxQmaVbj64+d6ITgdH0ByXTqyFZIMZVoIx/PsQJz49Ng7Kt/63AzmpqbaN7Zh6hVINj+iWuQ9VM1T2/OpKNGKoXgCcGrh7ubSNcsdFnXnrNe7zed8CvLjY9oViWDp8AW+TFRJBysmYGo8EP/8kM8B78A6nnBJ4d4AmKU3kyEXLWWnRxVeY7GWZVlxhX2FF2RrV4ryiwUSBvrZbVd0XN3vVdcLUmWdW3jKpH3ZhkFDBqK4=
