language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: sO0o1y5OhAfKnLB2FXfjZO5aoswQplWmzVntKsSFo9T+Hx/u4C1MnbixPjff5u0CXbNT0YNZMjCdjzli2XLTaM1JYXYhSYqHLXtOnKi23Ig5rtDP90/3rMfL8QOT/MQNLTfpkIkZSuFMBSejX8tHZNVaUT5XeUyE1hOBVTDJzkETgL8cvYoAWu+navrUn8dJigWWoWKo339vTxtlygydhktC4T0kn6PAYr6I+p0x5wH3xgtbrb+G77FO7izHVytNRHBzJ7DE22KHzVDT/DQAoGy0APEwfrAMoRGqzHveGBNwB+u7VarARPWFqASD9dL8OSKcr9fd9n0PwO5yrDBL+fy3zXisL+M0ekzl1rigQcs8YKZaZ+a+JJZSGL8rdwrYlBoSkwOtXEbDvpGfLuR9YLrM+ZtOhesHxQIWlMZJwE/bkZ8NL2xoNKS0YIlDhS0ZvvdHdn+VwWCl4wzEZgtZDzNIkNXavb5iOqocBMZSp3lOMRpu4zTRWpnyAcywOzvMcXZ2BETwk4AIzSkquMC8223lkP1bLJWWHU6u2KEvNXHQ2GmMFjIxSkLYdzVklzm6zI0WKSsAZXStaJkNisdPKknpVdyrO3uTRLj9JKMjSEhy4LcY8NXo5nTsBujBA91J3lcvuRmUOI9Xpk7gB2WZ9BFHfC16e/LuiXReh1ngdr0=
