language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: v0EGEy4nJaD8EB2yFiNPzkeuxG9fusqLj+s/9TqAs8b9kUf46SYBqJ/Z7Tx1JW3f3ad6Yqto8DPY4+ag/LaTor1hl6CNjiOFqLJr08DSDZyO6OuUHsjUXF2WoXZyr49yN24OKsuA7w6Paz8aAQVWe9pSplc756vmS3cQ9ZxmXZez/UIItRWXwU3tdQ9+TgmTi58End9AfiCPM4sHNXPK86cbmv9jy4v1nBw52lXPvvgHMBGW2RVL6dGvuubv8td9hNITzIrwv+zbAuITi4aV7Qy7KaCxR+4bVVo8iBfeJ5zwFouTKsT4cnZuFyITsjVX5Afsh0gpEhYh9JRz79R3i79BhEQzYX7AZrAUtffPD8zqqe/7FoDDyqBjePbE0DLB6r7ZeThX5wxYQNOyLL0YY/4L679LrrZWOKS/90F3xHnu/fEtirXVNm2q5VBb9lPtCsYc/llN0uraelwcPmFEqG+8L2ujGJ5WveKU9+YHHayF7rsshOaOpJZbKgk4xBf7hTeyDt998Ewqfx1H2zvSpvCrdReJPGzqNSJsBjqUIY4EVKnUSxrIetwFX2tKYSZrTnDS/mHZeLvIlFUS8hDQxHv3LmPyG7KrC/h2603C3KDz0M6y2FvQAWCkiOp44cADoQ7YW94IySxEvv5xn0ey5FoEsQ42DBVtI/NeKOyuW6w=
