language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key: AwdElC2CVaAeOEWk+PU9elrx7+SyWyHfkIyipoGM9fzO0xkG11UHLzFWHeyvh1yQVQHSZstqoXNjIoB0Vacu6Tvc2G4TJuvf5t0MA+w7tnXqsUNGIVogMQ1RolzXEISXYeFWbxlhQdRxJdrLGhIxVfX41F597OAGiqD5ynaeRnojNPDFSMERd74dFgdwJquGsvxOHA1LsO+CklBpND91oUhYtU/lkYCRge42sWGs7Fru4Tt+4xKCopacC0tLPb8yXsznw51zmg0AT+MbgWR+EiOXc8WZK0OmLTUhHiWeuNXMYdpeBhq+Hq70BghjiIAyXsVFDr7W5WG768EC3UsNcQdTgVK/w1tqE/eeR8SWYwrhGg4u/vvX6MmTI099ov7qZE48izxi8gVx8H0IzQE/K/QINQifLYDPq9iW2GBBSLGlAbluMLospicpdP/KtczQQGcsXP36q/+Z0p1Pfm0OFRj8mndziCpjIs0KfrtiXtYvj0gZE+eoFdE01II52c9Y7Ef8h4yxOvN/kEb7eNBSttbNo7nKwDoI5U8oDuwIn1AiHwGtNiiSv51FVSQ9ofblcTHbVR5pF//xW400B2fYd4JF/j2ZiF5uP7IFsNUz8ahJAEx/CJ4w3Lf/Bi60Id5UOQzMe+R4oZl88m8HI4GIVMc4lIgUBwOQNSC9fjGhulg=
